name: publish_conda

on:
  push:
    branches:
      - master
jobs:
  windows:
    runs-on: windows-2016
    strategy:
      matrix:
        python: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - name: submodules
      shell: bash -l {0}
      run: |
        git submodule update --init --recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: setup anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }} 
        activate-environment: loop    
    - name: Build package
      shell: powershell
      run: |
        conda install -c conda-forge conda-build scikit-build numpy cython
        conda build -c anaconda -c conda-forge -c loop3d --output-folder conda conda
    - name: upload
      shell: powershell
      env:
        ANACONDA_API_TOKEN: ${{ secrets.CONDA }}
      run: | 
        conda install anaconda-client
        anaconda upload --label main win-64/*.tar.bz2 
#   unix_package:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - uses: conda-incubator/setup-miniconda@v2
#         with:
#           auto-activate-base: true
#           installer-url: https://github.com/conda-forge/miniforge/releases/download/4.10.1-0/Miniforge-pypy3-4.10.1-0-Linux-x86_64.sh
#           channels: anaconda,conda-forge,loop3d,conda-forge/label/cf202003
#           python-version: 3.7

#       - name: Building and uploading m2l pkg for linux, osx and windows
#         shell: bash -l {0}
#         env:
#           ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
#         run: |
#             conda env list
#             conda install conda-build anaconda-client conda-verify -y
#             python setup.py develop
#             cd conda
#             python conda-build.py

  #windows_package:
    #runs-on: windows-2019
    #strategy:
      #matrix:
        #python: ['3.7']
    #steps:
      #- uses: actions/checkout@v2
      #- name: msbuild to path
        #uses: microsoft/setup-msbuild@v1.0.2
      #- uses: conda-incubator/setup-miniconda@v2
        #with:
          #python-version: ${{ matrix.python }} 
      #- name: conda build
        #shell: powershell
        #run: |
          #python --version
          #conda install -c conda-build anacona-client -y
          #conda build -c anaconda -c conda-forge -c loop3d -c --output-folder . .
      #- name: conda upload
        #shell: powershell
        #env:
          #ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        #run: | 
          #anaconda upload win-64/*.tar.bz2 

